import { initializeApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";
import { getStorage } from "firebase/storage";
import { getAuth } from "firebase/auth";

// Your web app's Firebase configuration
// We will replace this with the actual config generated by Firebase
const firebaseConfig = {
  apiKey: "AIzaSyDl2OmQBM5RrX4-u3MTHl1MAikafdQ82Yo",
  authDomain: "king-services-concrete.firebaseapp.com",
  projectId: "king-services-concrete",
  storageBucket: "king-services-concrete.firebasestorage.app",
  messagingSenderId: "244421876283",
  appId: "1:244421876283:web:8e001796416fa91f09da1e"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const db = getFirestore(app);
const storage = getStorage(app);
const auth = getAuth(app);

export { app, db, storage, auth };
