import { initializeApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";
import { getStorage } from "firebase/storage";
import { getAuth } from "firebase/auth";

// Your web app's Firebase configuration
// We will replace this with the actual config generated by Firebase
const firebaseConfig = {
  apiKey: "PLACEHOLDER_API_KEY",
  authDomain: "king-services-concrete.firebaseapp.com",
  projectId: "king-services-concrete",
  storageBucket: "king-services-concrete.appspot.com",
  messagingSenderId: "244421876283",
  appId: "PLACEHOLDER_APP_ID"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const db = getFirestore(app);
const storage = getStorage(app);
const auth = getAuth(app);

export { app, db, storage, auth };
